export default {
  LOADING: 'loading',

  LOGIN: 'Login',
  REGISTER: 'Register',

  HOME: 'MyTab',
  HOME_TAB: 'Home Tab',
  NOTIFICATIONS: 'Notifications',
  OTP: 'OTP Screen',
  ADD_PRODUCT: 'ADD_PRODUCT',
  AWAITING: 'AWAITING',
  CANCELED: 'CANCELED',
  AWAITINGPICKUUP: 'AWAITING PICKUP',
  SHIPPING: 'SHIPPING',
  DELIVERED: 'DELIVERED',
  ORDER_TAB: 'ORDER_TAB',
  DETAILS: 'DETAILS',
  ADD_STOCK: 'ADD_STOCK',
};
